### ISSUE TITLE
Generate.py breaks for Python 2.7.6

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/nlesc.github.io#8]
The following command mentioned in the README exits with error:
python generate.py phenology

Traceback (most recent call last):
  File "generate.py", line 52, in <module>
    main()
  File "generate.py", line 49, in main
    generate_organization(organization)
  File "generate.py", line 23, in generate_organization
    fn = '_organizations/' + org.login.lower() + '.md'
TypeError: cannot concatenate 'str' and 'NullObject' objects

The following patch solves the issue:

diff --git a/generate.py b/generate.py
index c9dfb82..28888fe 100644
--- a/generate.py
+++ b/generate.py
@@ -20,7 +20,7 @@ import github3
 def generate_organization(organization):
     gh = github3.GitHub()
     org = gh.organization(organization)
-    fn = '_organizations/' + org.login.lower() + '.md'
+    fn = '_organizations/' + str(org.login.lower()) + '.md'
     title = org.name
     if not title:
         title = org.login

**Comment by sverhoeven** [comment]
The GitHub organization should exist before running the `generate.py` script.

**Comment by romulogoncalves** [comment]
True, but it should report that organization does not exist, not exiting with error for robustness.
Don't you agree?
